no1=int(input("Enter 1st Number:-"))
no2=int(input("Enter 2nd Number:-"))
add=no1+no2
sub=no1+no2
mul=no1*no2
div=no1/no2
fdiv=no1//no2
modul=no1%no2
expo=no1**no2

print(f"Sum of {no1} and {no2} is {add}")
print(f"Substraction of {no1} and {no2} is {sub}")
print(f"Multiplication of {no1} and {no2} is {mul}")
print(f"Division of {no1} and {no2} is {div}")
print(f"Floor Division of {no1} and {no2} is {fdiv}")
print(f"Exponentiation of {no1} and {no2} is {expo}")